version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "sbe-encoder-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
resolve_image_repos = true
confirm_changeset = false

[default.local_invoke.parameters]
skip_pull_image = false

