[profile.default]
src = "../../../contracts/src"
out = "out"
libs = ["../../../contracts/lib"]
test = "../../../contracts/test"
script = "../../../contracts/script"
remappings = [
    "@openzeppelin/contracts/=../../../contracts/lib/openzeppelin-contracts/contracts/",
    "forge-std/=../../../contracts/lib/forge-std/src/"
]
ignored_error_codes = [1878, 5574]
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "./generated" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
